Lessons 10
olfies/TestGuru pull request #14
Opened 2023-10-09 22:25 UTC by olfies

2023-10-10 06:57 UTC, BubuntuClu requested changes

2023-10-10 06:57 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
тут не нужен колбэк, ты же в родительском добавил его

2023-10-10 06:57 UTC, BubuntuClu commented on app/models/test_passage.rb
> -    answer_ids ||= []
а это почему удалил?

2023-10-10 06:57 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +  <%= @test_passage.current_question.123  body %>
тут что-то лишнее

2023-10-10 06:57 UTC, BubuntuClu commented on db/migrate/20230517200301_create_users.rb
> +        t.string :email
нельзя задним числом править миграцию. удали этот код и через новую миграцию добавь поле.
так же не забудь индекс уникальности

2023-10-10 06:57 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "test_passageb", force: :cascade do |t|
что стало с именем таблицы?

2023-10-10 06:57 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "test_passages", force: :cascade do |t|
вообще тут что-то странное в файле происходит. нет миграций на изменения test_passages

2023-10-10 06:57 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def current_user
> Используйте объект текущего пользователя при старте прохождения теста

это сделал?

2023-10-10 06:57 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    def flash_message(flash)
где используется этот метод?

2023-10-10 06:57 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +      if flash[:alert]
а если не алерт будет?
тебе нужен код, который будет выводить любой тип флэша и сразу все что в нем есть

2023-10-10 06:57 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_save :set_next_question, if: :completed?
как будет работать этот код? в каком случае будет ставиться след вопрос?

2023-10-11 07:22 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.correct_questions += 1
читал код метода? зачем эта строка?

2023-10-11 07:22 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +       content_tag :p, message, class: "flash #{type}"
стоит еще проверять что сообщение присуствует во флэше, перед тем как его выводить

2023-10-11 07:24 UTC, BubuntuClu commented on db/migrate/20230517200301_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
не всею миграцию удалить надо. было, а только строку по добавление почты.
надо вернуть миграцию

2023-10-11 07:24 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "current_question_id"
где миграция на это изменение?

2023-10-11 07:24 UTC, BubuntuClu commented on db/schema.rb
> -  add_foreign_key "test_passages", "current_questions"
это куда пропало?

2023-10-11 07:24 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def current_user
с этим что?

2023-10-11 18:01 UTC, BubuntuClu requested changes

2023-10-11 18:01 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод не нужен больше, удали. не забывай делать рефакторинг когда, когда что-то меняешь

2023-10-11 18:01 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
как текущий код в хэлпере решает вопрос из комментария `стоит еще проверять что сообщение присуствует во флэше, перед тем как его выводить`? 
где проверка?

и еще вопрос - почему ты делаешь хэлпер про флэши в `session_helper` файле?

2023-10-11 18:01 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_save :set_next_question, if: :completed?
не ответил. можно комменты оставлять

2023-10-11 18:01 UTC, BubuntuClu commented on db/migrate/20231011162128_create_users.rb
> +class CreateUsers < ActiveRecord::Migration[6.1]
да, с пользователями ты путаницу сделал. у тебя миграции которые обращаются к пользователям происходят раньше чем ты создаешь саму таблицу.
надо с порядком файла разобраться в списке миграций

2023-10-11 20:41 UTC, olfies commented on app/models/test_passage.rb
> +  before_save :set_next_question, if: :completed?
before_save  это обратный вызов, который будет выполнен перед сохранением записи TestPassage. Он будет выполняться только если условие if completed? вернет тру. Метод completed? определяет, успешно ли прошел пользователь тест, сравнивая процент правильных ответов с порогом, установленным в SUCCESS_PERCENT.
Таким образом, set_next_question будет вызван перед сохранением записи TestPassage, только если пользователь успешно прошел тест, то есть, процент правильных ответов равен или превышает 85%.
Вроде дал ответ вам на ваш вопрос, но возможно я где-то ошибся и запутался

2023-10-11 20:49 UTC, olfies commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
проверку я четсно не знаю как сделать, а почему хэлпер про флэши делаю в session_helper сам не знаю мне казалось что разницы особо где это нахоидтся нету, но я создал новый хелпер flash и в новом коммите код перенес туда

2023-10-12 08:56 UTC, BubuntuClu commented on app/helpers/flash_helper.rb
> +module FlashHelper
как текущий код в хэлпере решает вопрос из комментария стоит еще проверять что сообщение присуствует во флэше, перед тем как его выводить?
где проверка?

2023-10-12 08:56 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_save :set_next_question, if: :completed?
1 - зачем ставить следующий вопрос у теста который прошли?
2 - как проходить тест, если вопросы не меняются?

2023-10-12 08:57 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
у тебя есть объект флэшей, это хэш. тебе надо взять конкретный хэш и посмотреть есть ли в нем сообщение какое-то.

все должно происходить в одной операции. зачем ты выделяешь `alert` от остальных флешей?

2023-10-12 08:58 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
мне казалось что разницы особо где это нахоидтся нету, - это не очевидное поведение. что в сессии лежит что-то про флэш

2023-10-14 17:54 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if @user && @user.authenticate(params[:session][:password])
что делает этот `if`? в нем нет условия на `true`

2023-10-14 17:54 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +        return
return не надо писать. последняя строка в методе всегда делает `return` сама

2023-10-17 07:35 UTC, BubuntuClu requested changes

2023-10-17 07:35 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +    <% flash.each do |message_type, message| %>
у тебя есть хэлпер `flash_message`, зачем тут "дублировать" его логику?
ну и если ты тут выводишь сообщения, и во вьюхах есть код про флэши, у тебя будет дважды выводится информация

2023-10-17 07:35 UTC, BubuntuClu commented on app/helpers/flash_helper.rb
> +      puts flash[:message] if flash.is_a?(Hash) && flash[:message]
это так и не исправил. в телеграме тебе писал что `puts` пишет в консоль, а тебе нужно отобразить оформленный код сообщения на странице

2023-10-24 16:06 UTC, merged